# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-20 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('nombre_personal', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=13)),
                ('direccion_calle', models.CharField(max_length=30)),
                ('numero_interior', models.CharField(max_length=50)),
                ('numero_exterior', models.IntegerField(blank=True)),
                ('codigo_postal', models.IntegerField()),
                ('entidad_federativa', models.CharField(max_length=30)),
                ('municipio', models.CharField(max_length=30)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(blank=True)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
