# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-21 21:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_interno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='codigo_postal',
            field=models.IntegerField(max_length=5, validators=[django.core.validators.RegexValidator(message='El Codigo Postal es invalido', regex='^\\+?1?\\d{9,5}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='numero_exterior',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='rfc',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='El RFC parece ser invalido', regex='^\\+?1?\\d{9,9}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El numero telefonico debe de ser de diez digitos', regex='^\\+?1?\\d{9,10}$')]),
        ),
    ]
